# -*- coding: utf-8 -*-
"""Internship Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EXtcc6DL-yON39T_PwmSgzf1QqYp4kwG
"""

pip install zxcvbn nltk

# @title 🛠️ Professional Password Security Toolkit (v2.0)
# @markdown Run this cell to initialize the Security Engine.

import itertools
import os
from zxcvbn import zxcvbn
from google.colab import files
from datetime import datetime

class PasswordSecurityEngine:
    """
    A professional-grade engine for password analysis and
    targeted dictionary generation.
    """
    def __init__(self):
        self.leet_map = {
            'a': ['4', '@'], 'e': ['3'], 'i': ['1', '!'],
            'o': ['0'], 's': ['5', '$'], 't': ['7']
        }
        self.results_log = []

    def analyze_strength(self, password):
        """Performs deep entropy analysis using zxcvbn."""
        data = zxcvbn(password)

        # Structure the report
        report = {
            "password": password,
            "score": data['score'],
            "entropy": data['guesses_log10'],
            "crack_time": data['crack_times_display']['offline_fast_hashing_1e10_per_second'],
            "warning": data['feedback']['warning'],
            "suggestions": data['feedback']['suggestions']
        }
        self._print_analysis_report(report)
        return report

    def generate_targeted_wordlist(self, seeds, years, filename="output.txt"):
        """Generates a professional wordlist using permutation logic."""
        wordlist = set()

        for seed in seeds:
            if not seed or len(seed) < 2: continue

            # Phase 1: Case Mutations
            variants = {seed.lower(), seed.capitalize(), seed.upper()}

            # Phase 2: LeetSpeak Transformations
            leet_variants = self._apply_leetspeak(seed.lower())
            variants.update(leet_variants)

            # Phase 3: Temporal & Symbolic Appendages
            for v in variants:
                wordlist.add(v)
                for year in years:
                    wordlist.add(f"{v}{year}")        # Buddy1995
                    wordlist.add(f"{v}{year[-2:]}")    # Buddy95
                    wordlist.add(f"{v}!{year}")       # Buddy!1995

        self._export_to_file(sorted(list(wordlist)), filename)
        return len(wordlist)

    def _apply_leetspeak(self, text):
        """Internal helper for recursive leetspeak substitution."""
        results = [text]
        for char, subs in self.leet_map.items():
            for res in results[:]:
                for sub in subs:
                    results.append(res.replace(char, sub))
        return results

    def _print_analysis_report(self, r):
        print(f"\n{'='*40}")
        print(f"🛡️ SECURITY AUDIT: {r['password']}")
        print(f"{'='*40}")
        status = ["CRITICAL", "WEAK", "FAIR", "GOOD", "STRONG"][r['score']]
        print(f"Result: {status} ({r['score']}/4)")
        print(f"Entropy: {r['entropy']:.2f} (log10)")
        print(f"Est. Crack Time: {r['crack_time']}")
        if r['warning']: print(f"⚠️ {r['warning']}")
        for s in r['suggestions']: print(f"💡 {s}")

    def _export_to_file(self, data, filename):
        with open(filename, "w") as f:
            f.write("\n".join(data))
        print(f"\n✅ Wordlist compiled: {len(data)} entries.")
        print(f"💾 File: {os.path.abspath(filename)}")

# --- INTERFACE LAYER (Colab Forms) ---

# @markdown ### ⚙️ Execution Settings
mode = "Full Audit & Wordlist" # @param ["Analysis Only", "Wordlist Only", "Full Audit & Wordlist"]
user_test_password = "Password123" # @param {type:"string"}

# @markdown ### 👤 Target Profiling
target_name = "John" # @param {type:"string"}
target_pet = "Buddy" # @param {type:"string"}
birth_year = "1990" # @param {type:"string"}

# Instantiate the engine
engine = PasswordSecurityEngine()

if "Analysis" in mode or "Full" in mode:
    engine.analyze_strength(user_test_password)

if "Wordlist" in mode or "Full" in mode:
    count = engine.generate_targeted_wordlist(
        seeds=[target_name, target_pet],
        years=[birth_year, str(datetime.now().year)],
        filename="internship_project_output.txt"
    )
    files.download("internship_project_output.txt")

